version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - .:/app
      - app-node_modules:/app/node_modules

volumes:
    app-node_modules: